# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfe15c1c772c502c879741ada9a1942e"
name = "bulk-products"
application_url = "https://blast-there-accomplish-cbs.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ecom-v2-technologies.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://blast-there-accomplish-cbs.trycloudflare.com/auth/callback",
  "https://blast-there-accomplish-cbs.trycloudflare.com/auth/shopify/callback",
  "https://blast-there-accomplish-cbs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
